# Checking if output Stokes vectors are the same as input Stokes - they are not the same

In [1]:
import numpy as np
import sys
sys.path.insert(0, '../python/')
import angles
import instrument_mm
import stokes

# Define observer parameters
observer_latitude = 20.0  # Latitude of Mauna Kea in degrees
observer_longitude = -155.5  # Longitude of Mauna Kea in degrees

# Define target parameters
targets = [
    {"ra": 45.0, "dec": -50.0},  # RA 3h (45°), Dec -50°
    {"ra": 45.0, "dec": -20.0},  # RA 3h (45°), Dec -20°
    {"ra": 45.0, "dec": 15.0},   # RA 3h (45°), Dec 15°
]

# Polarization levels to inject (0.01%, 0.1%, and 1%)
polarization_levels = [0.0001, 0.001, 0.01]  # Convert percentages to decimal form

# Observation date and time
observation_date = "2460601.5"  # JD for 10/31/2024
observation_time = "14:00:00"   # UT time to get peak at midnight HST

# Run the simulation
for target in targets:
    print("*************************")
    print(f"Target RA: {target['ra']}°, Dec: {target['dec']}°")
    
    for pol in polarization_levels:
        # Inject Q and U polarization levels
        Q_injected = pol
        U_injected = 0
        
        # Calculate the parallactic angle
        pa = angles.calculate_parallactic_angle(
            ra=target["ra"], 
            dec=target["dec"], 
            ut=observation_time, 
            jd_str=observation_date, 
            observer_latitude=observer_latitude, 
            observer_longitude=observer_longitude
        )
        
        # Calculate the altitude for each target at the given date and time
        H = angles.calculate_hour_angle(
            ra=target["ra"], 
            observer_longitude=observer_longitude, 
            ut=observation_time, 
            jd_str=observation_date
        )
        altitude = angles.calculate_altitude(
            phi=observer_latitude, 
            delta=target["dec"], 
            H=H
        )
        
        # Calculate Q and U using the modified calculate_Q_and_U function with calculated altitude
        Q_retrieved, U_retrieved, intensities = \
            instrument_mm.calculate_Q_and_U(
                Q=Q_injected, 
                U=U_injected, 
                pa=pa, 
                altitude=altitude
            )
        
        # Output results
        print(f"Injected Polarization: {pol * 100:.2f}%")
        print(f"Retrieved Q: {Q_retrieved:.6f}, Retrieved U: {U_retrieved:.6f}")
        print("Intensities: " + str(intensities))


*************************
Target RA: 45.0°, Dec: -50.0°
o stokes: [[0.49162857]
 [0.49162857]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48545531]
 [-0.48545531]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49162857465851273
e intensity: 0.48545530963306427
Injected Polarization: 0.01%
Retrieved Q: -0.001341, Retrieved U: 0.001360
Intensities: [[0.49162857 0.49295789 0.49292308 0.49159377]
 [0.48545531 0.48414585 0.48412961 0.48543907]]
o stokes: [[0.4920209]
 [0.4920209]
 [0.       ]
 [0.       ]]
e stokes: [[ 0.48505988]
 [-0.48505988]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49202090184001257
e intensity: 0.4850598760370412
Injected Polarization: 0.10%
Retrieved Q: -0.000537, Retrieved U: 0.000964
Intensities: [[0.4920209  0.49275593 0.49253153 0.49179651]
 [0.48505988 0.48432804 0.48452093 0.48525277]]
o stokes: [[0.49594417]
 [0.49594417]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48110554]
 [-0.48110554]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.4959441736550106
e int

# Previous block but with calculate_Q_and_U_observing_sequence 

In [2]:
import numpy as np
import sys
sys.path.insert(0, '../python/')
import angles
import instrument_mm
import stokes

# Define observer parameters
observer_latitude = 20.0  # Latitude of Mauna Kea in degrees
observer_longitude = -155.5  # Longitude of Mauna Kea in degrees

# Define target parameters
targets = [
    {"ra": 45.0, "dec": -50.0},  # RA 3h (45°), Dec -50°
    {"ra": 45.0, "dec": -20.0},  # RA 3h (45°), Dec -20°
    {"ra": 45.0, "dec": 15.0},   # RA 3h (45°), Dec 15°
]

# Polarization levels to inject (0.01%, 0.1%, and 1%)
polarization_levels = [0.0001, 0.001, 0.01]  # Convert percentages to decimal form

# Observation date and time
observation_date = "2460601.5"  # JD for 10/31/2024
observation_time = "14:00:00"   # UT time to get peak at midnight HST

# Run the simulation
for target in targets:
    print("*************************")
    print(f"Target RA: {target['ra']}°, Dec: {target['dec']}°")
    
    for pol in polarization_levels:
        # Inject Q and U polarization levels
        Q_injected = pol
        U_injected = 0
        
        # Calculate the parallactic angle
        pa = angles.calculate_parallactic_angle(
            ra=target["ra"], 
            dec=target["dec"], 
            ut=observation_time, 
            jd_str=observation_date, 
            observer_latitude=observer_latitude, 
            observer_longitude=observer_longitude
        )
        
        # Calculate the altitude for each target at the given date and time
        H = angles.calculate_hour_angle(
            ra=target["ra"], 
            observer_longitude=observer_longitude, 
            ut=observation_time, 
            jd_str=observation_date
        )
        altitude = angles.calculate_altitude(
            phi=observer_latitude, 
            delta=target["dec"], 
            H=H
        )
        
        # Calculate Q and U using the modified calculate_Q_and_U function with calculated altitude
        Q_retrieved, U_retrieved, intensities = \
            instrument_mm.calculate_Q_and_U_observing_sequence(
                Q=Q_injected, 
                U=U_injected, 
                ra=target["ra"], 
                dec=target["dec"], 
                ut_start=observation_time, 
                jd_str=observation_date, 
                observer_latitude=observer_latitude, 
                observer_longitude=observer_longitude,
                t_int = 0
            )
        
        # Output results
        print(f"Injected Polarization: {pol * 100:.2f}%")
        print(f"Retrieved Q: {Q_retrieved:.6f}, Retrieved U: {U_retrieved:.6f}")
        print("Intensities: " + str(intensities))


*************************
Target RA: 45.0°, Dec: -50.0°
o stokes: [[0.49162857]
 [0.49162857]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48545531]
 [-0.48545531]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49162857465851273
e intensity: 0.48545530963306427
Injected Polarization: 0.01%
Retrieved Q: -0.001341, Retrieved U: 0.001360
Intensities: [[0.49162857 0.49295789 0.49292308 0.49159377]
 [0.48545531 0.48414585 0.48412961 0.48543907]]
o stokes: [[0.4920209]
 [0.4920209]
 [0.       ]
 [0.       ]]
e stokes: [[ 0.48505988]
 [-0.48505988]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49202090184001257
e intensity: 0.4850598760370412
Injected Polarization: 0.10%
Retrieved Q: -0.000537, Retrieved U: 0.000964
Intensities: [[0.4920209  0.49275593 0.49253153 0.49179651]
 [0.48505988 0.48432804 0.48452093 0.48525277]]
o stokes: [[0.49594417]
 [0.49594417]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48110554]
 [-0.48110554]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.4959441736550106
e int

# Testing calculate_Q_and_U_observing_sequence

In [4]:
import numpy as np
import angles
import instrument_mm

# Define observer parameters
observer_latitude = 20.0  # Latitude of Mauna Kea in degrees
observer_longitude = -155.5  # Longitude of Mauna Kea in degrees

# Define target parameters
targets = [
    {"ra": 45.0, "dec": -50.0},  # RA 3h (45°), Dec -50°
    {"ra": 45.0, "dec": -20.0},  # RA 3h (45°), Dec -20°
    {"ra": 45.0, "dec": 15.0},   # RA 3h (45°), Dec 15°
]

# Polarization levels to inject (0.01%, 0.1%, and 1%)
polarization_levels = [0.0001, 0.001, 0.01]  # Convert percentages to decimal form

# Observation date and time
observation_date = "2460601.5"  # JD for 10/31/2024
observation_time = "14:00:00"   # UT time to get peak at midnight HST
t_int = 1  # Integration time in seconds

# Run the simulation
for target in targets:
    print("*************************")
    print(f"Target RA: {target['ra']}°, Dec: {target['dec']}°")
    
    for pol in polarization_levels:
        # Inject Q and U polarization levels
        Q_injected = pol  # Q component for polarization
        U_injected = 0   # Assume U component is 0 for simplicity
        
        # Retrieve Q and U using the calculate_Q_and_U_observing_sequence function
        Q_retrieved, U_retrieved, intensities = instrument_mm.calculate_Q_and_U_observing_sequence(
            ra=target["ra"], 
            dec=target["dec"], 
            observer_latitude=observer_latitude, 
            observer_longitude=observer_longitude, 
            jd_str=observation_date, 
            ut_start=observation_time, 
            t_int=t_int, 
            Q=Q_injected, 
            U=U_injected
        )
        
        # Output results
        print(f"Injected Polarization: {pol * 100:.2f}%")
        print(f"Retrieved Q: {Q_retrieved:.6f}, Retrieved U: {U_retrieved:.6f}\n")


*************************
Target RA: 45.0°, Dec: -50.0°
o stokes: [[0.49162857]
 [0.49162857]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48545531]
 [-0.48545531]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49162857465851273
e intensity: 0.48545530963306427
Injected Polarization: 0.01%
Retrieved Q: -0.001341, Retrieved U: 0.001360

o stokes: [[0.4920209]
 [0.4920209]
 [0.       ]
 [0.       ]]
e stokes: [[ 0.48505988]
 [-0.48505988]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.49202090184001257
e intensity: 0.4850598760370412
Injected Polarization: 0.10%
Retrieved Q: -0.000537, Retrieved U: 0.000964

o stokes: [[0.49594417]
 [0.49594417]
 [0.        ]
 [0.        ]]
e stokes: [[ 0.48110554]
 [-0.48110554]
 [ 0.        ]
 [ 0.        ]]
o intensity: 0.4959441736550106
e intensity: 0.4811055400768107
Injected Polarization: 1.00%
Retrieved Q: 0.007501, Retrieved U: -0.002993

*************************
Target RA: 45.0°, Dec: -20.0°
o stokes: [[0.48897358]
 [0.48897358]
 [0.        ]
 [0