In [2]:
import sys
sys.path.insert(0, '../python/')
import angles
import instrument_mm
import stokes
import numpy as np

HWP_angs = np.array([0, 22.5, 45, 67.5])

Q_in = 0.3
U_in = 0.7
Q_out, U_out, Q_wollaston_and_HWP, U_wollaston_and_HWP, intensities, \
        intensities_wollaston_and_HWP = instrument_mm.calculate_Q_and_U(Q = Q_in, 
    U = U_in, pa = 0, altitude = 0, delta_HWP = 0.5, normalize = True)

print("Q: " + str(Q_out))
print("U: " + str(U_out))
print("Q (Only Wollaston and HWP): " + str(Q_wollaston_and_HWP))
print("U (Only Wollaston and HWP): " + str(U_wollaston_and_HWP))
# print(intensities_wollaston_and_HWP)

print(intensities)
print(intensities_wollaston_and_HWP)

0.65
Q: 0.3
U: 0.7
Q (Only Wollaston and HWP): 0.3
U (Only Wollaston and HWP): 0.7
[[0.65 0.85 0.35 0.15]
 [0.35 0.15 0.65 0.85]]
[[0.65 0.85 0.35 0.15]
 [0.35 0.15 0.65 0.85]]
